// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3DD8PCiQvwygtJtSyB6O-VeRhteLBiRM',
    appId: '1:727693847562:web:8adea80554d4421fe8c3f3',
    messagingSenderId: '727693847562',
    projectId: 'liber-maniac',
    authDomain: 'liber-maniac.firebaseapp.com',
    storageBucket: 'liber-maniac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtO7DUAX2LED-skOf84H2Ol4Pups8GOj4',
    appId: '1:727693847562:android:36c036ea4e20f4aae8c3f3',
    messagingSenderId: '727693847562',
    projectId: 'liber-maniac',
    storageBucket: 'liber-maniac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9O5xYOeP9x0M4RO3_OD9fYy2g_C8BlAE',
    appId: '1:727693847562:ios:c6e822d08f705531e8c3f3',
    messagingSenderId: '727693847562',
    projectId: 'liber-maniac',
    storageBucket: 'liber-maniac.appspot.com',
    iosBundleId: 'com.example.liberManiac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9O5xYOeP9x0M4RO3_OD9fYy2g_C8BlAE',
    appId: '1:727693847562:ios:c6e822d08f705531e8c3f3',
    messagingSenderId: '727693847562',
    projectId: 'liber-maniac',
    storageBucket: 'liber-maniac.appspot.com',
    iosBundleId: 'com.example.liberManiac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3DD8PCiQvwygtJtSyB6O-VeRhteLBiRM',
    appId: '1:727693847562:web:4161b1149d47b61de8c3f3',
    messagingSenderId: '727693847562',
    projectId: 'liber-maniac',
    authDomain: 'liber-maniac.firebaseapp.com',
    storageBucket: 'liber-maniac.appspot.com',
  );
}
